# Site wide configuration

# Title for every page

title: Literate Programming with Docker

# mathjax: false # Turn off if you really want to !

logo: Logo.jpg
logo_size: 200px

# Navigation links for the yellow banner (v. short names are a good idea)

# Note: the links need to work within the 'jupyter notebook' filesystem which
#       is a little different from the arrangements of the files on disk
#       /files/X.yyy points to _site/X.yyy
#       /notebooks/NBk/X.ipynb points to _site/NBk/X.ipynb but assumes the file is a runnable notebook
#       /edit/dir/X.yyy brings up the file _site/dir/X.yyy in the text editor

navigation:
    - url:  /files/Instructions.html
      name: Guide

    - url:  /files/WritingContent.html
      name: Format

    - url:  /notebooks/ExampleContent/Notebooks/StartHere.ipynb
      name: Notebooks

    - url:  /notebooks/ExampleContent/Notebooks/
      name: File Browser

# Site owner / contact person

owner:
  name: "Louis Moresi"

  # This list populates the page footer
  contact_list:

      - url: mailto:louis.moresi@unimelb.edu.au
        description: email

      - url: http://www.moresi.info
        description: www.moresi.info

      - url: tel:+61383441217
        description: office phone


include: [".htaccess", "_assets"]

exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", ".Procfile", "Dockerfile"]
