site_name: Literate Programming & Docker
site_author: Louis Moresi
site_dir: www

# theme over-ride

theme_dir: jupyter-server-theme

# Layout of pages

use_directory_urls: False
include_next_prev: False

# Theme
theme: flatly

pages:
- index.md
- Map.md
- About:
    - 'How to write a new page' : WritingContent.md
    - 'Installation instructions' : Instructions.md

# Mathematics

extra_javascript:
  - http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - js/mathjax-local-config.js


## Here is how to add extra (external) links to the navigation bar
##
## 1) Add a link to the nav bar
##     The item you add is a two-member list: ["Name for the link", "url"]
## 2) Add a new menu item to the nav bar
##     The item you add is a three-or-more-member list with a name for the menu item as the first member
##     and subsequent entries being lists of names / urls as above:
##     [ "Menu name", ["Menu item 1 name", "Menu item 1 url"], ["Menu item 2 name", "Menu item 2 url"], ... ]
##


extra:
    nav_links:
        - ["Live Content",
            ["Notebooks", "/notebooks/Notebooks" ],
            ["Terminal", "/terminals/1" ]
          ]
        - ["Source Code", "/notebooks/docs"]
